### ISSUE TITLE
fig05_06 uniform_int_distribution can't be const

### ISSUE THREAD

**Issue by jbruck** [pdeitel/CPlusPlus20FundamentalsLiveLessons#2]
I am learning through your video course 😁👍

I found that msvc 2022 compiler compiles fig05_06 as provided, but g++ MSYS2 11.2.0 gives an error. 

Removing const from line 15 fixes this.

**Comment by pdeitel** [comment]
Hope you're enjoying the videos! Thanks for pointing this out. I just fixed this in the book the other day. We're about two weeks from sending C++20 for Programmers to publication. Then I'll be re-recording the videos and adding in the missing lessons (the order of those two pieces is still to be determined). I'll have about 50+ hours of video once I am done. And I'll add at least two Full Throttle live courses based on these products.
